import QtQuick
import QtMultimedia
import QtQuick.Controls
import QtQuick.Layouts
Item {
    Rectangle{
        // anchors.fill:parent
        Image{
            id:tubiao
            source:"images/ims.png"
            width:650
            height:250
            // anchors.horizontalCenter: parent.horizontalCenter
            x:290
            y:-20
          }
        Image{
            id:zuo
            source:"images/zuo.png"
            width:350
            height:550
            x:-19
            y:220
          }
        Image{
            id:you
            source:"images/you.png"
            width:350
            height:650
            x:859
            y:95
          }
        Image{
            id:duo
            source:"images/duo.png"
            width:150
            height:300
            x:-20
            y:-15
          }
        Image{
            id:duo1
            source:"images/duo.png"
            width:150
            height:300
            x:100
            y:-15
          }
        Image{
            id:dt1
            source:"images/dt3.png"
            width:60
            height:120
            x:45
            y:-15
          }
        Image{
            id:dt2
            source:"images/dt3.png"
            width:60
            height:120
            x:15
            y:10
          }
        Image{
            id:dt3
            source:"images/dt3.png"
            width:60
            height:120
            x:65
            y:10
          }
        Image{
            id:dt0
            source:"images/dt3.png"
            width:60
            height:120
            x:25
            y:-15
          }
        Image{
            id:dt4
            source:"images/dt2.png"
            width:60
            height:120
            x:-10
            y:-15
          }
        Image{
            id:dt5
            source:"images/dt2.png"
            width:60
            height:120
            x:95
            y:-15
          }
        Image{
            id:dt6
            source:"images/dt2.png"
            width:60
            height:120
            x:105
            y:15
          }
        Image{
            id:dt7
            source:"images/dt2.png"
            width:60
            height:120
            x:145
            y:-15
          }
        Image{
            id:qiu3
            source:"images/qiu3.png"
            width:50
            height:50
            x:-15
            y:695
          }
        Image{
            id:qiu4
            source:"images/qu4.png"
            width:50
            height:50
            x:25
            y:695
          }
        Image{
            id:qiu
            source:"images/qiu3.png"
            width:50
            height:50
            x:55
            y:695
          }
        Image{
            id:lihua
            source:"images/lihua.png"
            width:200
            height:500
            x:65
            y:300
          }
        Image{
            id:qiu1
            source:"images/qu4.png"
            width:50
            height:50
            x:230
            y:695
          }
        Image{
            id:qiu2
            source:"images/qiu3.png"
            width:50
            height:50
            x:200
            y:695
          }
        Image{
            id:qiu5
            source:"images/qiu3.png"
            width:50
            height:50
            x:170
            y:695
          }
        Image{
            id:cao
            source:"images/cao1.png"
            width:50
            height:50
            x:0
            y:650
          }
        Image{
          id:cao1
          source:"images/cao2.png"
          width:50
          height:50
          x:40
          y:630
        }
        Image{
          id:cao2
          source:"images/cao1.png"
          width:50
          height:50
          x:135
          y:570
        }
        Image{
          id:cao3
          source:"images/cao3.png"
          width:50
          height:50
          x:175
          y:570
        }
        Image{
          id:cao4
          source:"images/cao3.png"
          width:50
          height:50
          x:160
          y:695
        }
        Image{
          id:cao5
          source:"images/cao2.png"
          width:50
          height:50
          x:140
          y:695
        }
        Image{
          id:cao6
          source:"images/cao3.png"
          width:50
          height:50
          x:120
          y:695
        }
        Image{
          id:cao7
          source:"images/cao2.png"
          width:50
          height:50
          x:100
          y:695
        }
        Image{
          id:cao8
          source:"images/cao3.png"
          width:50
          height:50
          x:80
          y:695
        }
        Image{
          id:shuhua
          source:"images/shuhua.png"
          width:250
          height:300
          x:1000
          y:450
        }
        Image{
          id:he
          source:"images/he.png"
          width:150
          height:200
          x:900
          y:550
          z:1
        }
        Image{
          id:lv
          source:"images/lvteng.png"
          width:150
          height:200
          x:1000
          y:-5
        }
        Image{
          id:lv1
          source:"images/lvteng.png"
          width:150
          height:200
          x:1070
          y:-5
        }
        Image{
          id:lv2
          source:"images/lvteng.png"
          width:150
          height:200
          x:1120
          y:-5
        }
        Image{
          id:cao9
          source:"images/cao3.png"
          width:50
          height:50
          x:1155
          y:695
        }
        Image{
          id:cao10
          source:"images/cao2.png"
          width:50
          height:50
          x:1125
          y:695
        }
        Image{
          id:cao11
          source:"images/cao3.png"
          width:50
          height:50
          x:1095
          y:695
          z:1
        }
        Image{
          id:cao12
          source:"images/cao2.png"
          width:50
          height:50
          x:1065
          y:695
        }
        Image{
          id:cao13
          source:"images/cao3.png"
          width:50
          height:50
          x:1035
          y:695
        }
        Image{
          id:cao14
          source:"images/cao2.png"
          width:50
          height:50
          x:1015
          y:695
        }
        Image{
          id:cao15
          source:"images/cao3.png"
          width:50
          height:50
          x:985
          y:695
        }
        Image{
          id:cao16
          source:"images/cao3.png"
          width:50
          height:50
          x:885
          y:695
        }
        Image{
          id:cao17
          source:"images/cao2.png"
          width:50
          height:50
          x:855
          y:695
        }
        Image{
          id:cao18
          source:"images/cao2.png"
          width:50
          height:50
          x:865
          y:652
        }
        Image{
          id:cao19
          source:"images/cao1.png"
          width:50
          height:50
          x:900
          y:625
        }
        Image{
          id:cao20
          source:"images/cao3.png"
          width:50
          height:50
          x:930
          y:625
        }
        Image{
          id:hua
          source:"images/hua2.png"
          width:50
          height:50
          x:1095
          y:670
        }
        // Image{
        //   id:hua1
        //   source:"images/hua1.png"
        //   width:50
        //   height:150
        //   x:1145
        //   y:620
        // }
        Image{
          id:lv3
          source:"images/lvteng.png"
          width:150
          height:200
          x:1140
          y:5
        }
        Image{
          id:lv4
          source:"images/lvteng.png"
          width:150
          height:200
          x:1040
          y:5
        }
        Image{
          id:lv5
          source:"images/lvteng.png"
          width:150
          height:200
          x:940
          y:-5
        }
        Image{
            id:huo
            source:"images/yinghuo.png"
            width:200
            height:300
            x:100
            y:200
        }
        Image{
            id:huo1
            source:"images/yinghuo.png"
            width:200
            height:300
            x:800
            y:500
            z:2
        }
    }
}
